version: 3.8
services:

#    elasticsearch:
#        image: elasticsearch:8.11.1
#        environment:
#            — discovery.type=single-node
#        ports:
#            — 9200:9200
#        networks: 
#            - elk-stack
    kibana:
        image: kibana:8.12.0
        ports:
            — 5601:5601
        depends_on:
            — elasticsearch
        networks: 
            - elk-stack
networks: 
    elk-stack:
