FROM redis:7.2.5-alpine
EXPOSE 6379
#using command/entry-point in shell mod
ENTRYPOINT ["/bin/sh", "-c", "echo yes | \
    redis-cli --cluster create redis1:6379 redis2:6379 redis3:6379 redis4:6379 redis5:6379 redis6:6379 --cluster-replicas 1 && \
    echo \"control-plane is ready\" ! && \
    /bin/sh"]

