version: '3.8'
services:
  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#     - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
  linux-node-exporter:
    restart: unless-stopped
    image: prom/node-exporter
    container_name: linux-node-exporter
    ports:
      - 9098:9100
